version: '3.4'
services:
  hornet:
    build:
      context: .
      dockerfile: Dockerfile
    image: iota/hornet
    command: ["hornet", "-c", "/home/ubuntu/hornet/config/config"]
    volumes:
      - ./config:/home/ubuntu/hornet/config
    ports: 
     - "14265:14265"
     - "15600:15600"
     - "14626:14626"


