version: '3.4'
services:
  hornet:
    build:
      context: .
      dockerfile: Dockerfile
    image: iota/hornet
    command: ["hornet", "-c", "/etc/hornet/config"]
    volumes:
      - ./hornet/config:/etc/hornet


