version: '3.4'
services:
  hornet:
    build:
      context: .
      dockerfile: Dockerfile
    image: iota/hornet
    command: ["hornet", "-d", "/var/lib/hornet"]
    volumes:
      - ./config:/var/lib/hornet
    ports:
     - "14265:14265"
     - "15600:15600"
     - "14626:14626"