version: "3.4"
services:
  hornet:
    build:
      context: ../
      dockerfile: Dockerfile
    image: iota/hornet
    command: >
      bash -c "cd /var/lib/hornet &&
      sudo chown hornet: /var/lib/hornet/ -R &&
      sudo -u hornet COO_SEED="${COO_SEED}" hornet tool merkle"
    volumes:
      - ../config:/var/lib/hornet