version: "3.4"
services:
  hornet:
    build:
      context: ../
      dockerfile: Dockerfile
    image: iota/hornet
    command: > 
      bash -c "cd /var/lib/hornet &&
      sudo -u hornet COO_SEED="$${COO_SEED}" hornet tool merkle | grep -o '[A-Z9]*$' | sudo tee coordinator_address.txt"
    volumes:
      - ../config:/var/lib/hornet
    ports:
      - "14265:14265"
      - "15600:15600"
      - "14626:14626"
    

